### ISSUE TITLE
Putting a GeneratingFlower near a MechanicalManaPool will make server crashed!

### ISSUE THREAD

**Issue by MidCoard** [MelanX/botanical-machinery#45]
**Versions**

Minecraft: 1.16.5
Forge: 36.2.2
Botania: 1.16.5-419
Botanical Machinery: 0.4.1
LibX: 1.0.76
Modpack: 

**Describe the bug**

Putting a GeneratingFlower near a MechanicalManaPool will make server crashed!
This is a ClassCastException. The TIleMechanicalManaPool doesn't implement IManaCollector.

java.lang.ClassCastException: de.melanx.botanicalmachinery.blocks.tiles.TileMechanicalManaPool cannot be cast to vazkii.botania.api.mana.IManaCollector
	at vazkii.botania.api.subtile.TileEntityGeneratingFlower.emptyManaIntoCollector(TileEntityGeneratingFlower.java:151) ~[botania:1.16.5-418] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.botania.api.subtile.TileEntityGeneratingFlower.tickFlower(TileEntityGeneratingFlower.java:73) ~[botania:1.16.5-418] {re:classloading,pl:runtimedistcleaner:A}
	at vazkii.botania.common.block.subtile.generating.SubTileHydroangeas.tickFlower(SubTileHydroangeas.java:53) ~[botania:1.16.5-418] {re:classloading}
	at vazkii.botania.api.subtile.TileEntitySpecialFlower.func_73660_a(TileEntitySpecialFlower.java:120) ~[botania:1.16.5-418] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:hitbox,pl:runtimedistcleaner:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] {}

**How to reproduce**

1. place a MechanicalManaPool
2. place a GeneratingFlower near it
3. server crashes and crashes again

**Expected behavior**

**Screenshots**

**Comment by MelanX** [comment]
fixed in a3adffb91f9b19c20466f30900890a6af1be9bfc
